<?php

new Meta_Box(array(
    'id_meta' => 'info_kowowork',
    'name_meta' => 'Налаштування полів сторінки',
    'post_type' => 'page',
    'file_name' => 'page-kowowork.php',
    'meta_array' => array(

        'left_block_title' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => true,
            'title' => 'Заголовок блоку',
            'placeholder' => 'Приклад - Робочі місця',
            'class' => '',
        ),
        'left_block_image' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'img',
            'size' => 'medium',
            'title' => 'Основне зображення на блок',
            'placeholder' => '',
            'class' => 'meta-image hidden',
            'button' => array(
                'title' => 'Вибрати файл зображення',
                'class' => 'img-button',
            ),
        ),
        'left_block_image_hover' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'img',
            'size' => 'medium',
            'title' => 'Зображення, яке з\'являється при наведенні курсору',
            'placeholder' => '',
            'class' => 'meta-image hidden',
            'button' => array(
                'title' => 'Вибрати файл зображення',
                'class' => 'img-button',
            ),
        ),

        'center_block_title' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => true,
            'title' => 'Заголовок блоку',
            'placeholder' => 'Приклад - Зони відпочинку',
            'class' => '',
        ),
        'center_block_image' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'img',
            'size' => 'medium',
            'title' => 'Основне зображення на блок',
            'placeholder' => '',
            'class' => 'meta-image hidden',
            'button' => array(
                'title' => 'Вибрати файл зображення',
                'class' => 'img-button',
            ),
        ),
        'center_block_image_hover' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'img',
            'size' => 'medium',
            'title' => 'Зображення, яке з\'являється при наведенні курсору',
            'placeholder' => '',
            'class' => 'meta-image hidden',
            'button' => array(
                'title' => 'Вибрати файл зображення',
                'class' => 'img-button',
            ),
        ),

        'right_block_title' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => true,
            'title' => 'Заголовок блоку',
            'placeholder' => 'Приклад - Кухня',
            'class' => '',
        ),
        'right_block_image' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'img',
            'size' => 'medium',
            'title' => 'Основне зображення на блок',
            'placeholder' => '',
            'class' => 'meta-image hidden',
            'button' => array(
                'title' => 'Вибрати файл зображення',
                'class' => 'img-button',
            ),
        ),
        'right_block_image_hover' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'img',
            'size' => 'medium',
            'title' => 'Зображення, яке з\'являється при наведенні курсору',
            'placeholder' => '',
            'class' => 'meta-image hidden',
            'button' => array(
                'title' => 'Вибрати файл зображення',
                'class' => 'img-button',
            ),
        ),


        'work_rules_title' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => true,
            'title' => 'Заголовок секції',
            'placeholder' => 'Приклад - Правила роботи',
            'class' => '',
        ),
        'rule_name' => array(
            'clone' => true,
            'delete' => true,
            'input' => 'text',
            'required' => true,
            'title' => 'Назва правила',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),
        'rule_description' => array(
            'clone' => true,
            'delete' => true,
            'input' => 'text',
            'required' => false,
            'title' => 'Пояснення правила',
            'placeholder' => 'Заповніть це поле при потребі',
            'class' => '',
        ),

        'accessories_title' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => true,
            'title' => 'Заголовок секції',
            'placeholder' => 'Приклад - KOWO має:',
            'class' => '',
        ),

        'accessory_name' => array(
            'clone' => true,
            'delete' => true,
            'input' => 'text',
            'required' => false,
            'title' => 'Назва обладнання',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),

        'accessory_icon' => array(
            'clone' => true,
            'delete' => true,
            'input' => 'img',
            'title' => 'Назва файлу з іконкою (директорія розташування -> Папка теми/img/svg/)',
            'placeholder' => 'Введіть назву файлу разом з розширенням',
            'class' => '',
        ),

        'faq_title' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => true,
            'title' => 'Заголовок секції',
            'placeholder' => 'Приклад - Поширені питання',
            'class' => '',
        ),
        'faq_question' => array(
            'clone' => true,
            'delete' => true,
            'input' => 'text',
            'required' => true,
            'title' => 'Назва питання',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),
        'faq_answer' => array(
            'clone' => true,
            'delete' => true,
            'input' => 'text',
            'required' => true,
            'title' => 'Відповідь на питання',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),

        'section_pay_title' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => false,
            'title' => 'Заголовок секції',
            'placeholder' => 'Приклад - Оплата коворкінгу',
            'class' => '',
        ),
        'pay_main_text' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => false,
            'title' => 'Основний текст секції',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),
        'pay_btn_left' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => false,
            'title' => 'Текст лівої кнопки оплати',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),
        'pay_btn_center' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => false,
            'title' => 'Текст центральної кнопки оплати',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),
        'pay_btn_right' => array(
            'clone' => false,
            'delete' => false,
            'input' => 'text',
            'required' => false,
            'title' => 'Текст правої кнопки оплати',
            'placeholder' => 'Будь-ласка, заповніть це поле',
            'class' => '',
        ),

    ),
    'groups' => array(
        array('left_block_title'),
        array ('left_block_image'),
        array('left_block_image_hover'),
        array('center_block_title'),
        array('center_block_image'),
        array('center_block_image_hover'),
        array('right_block_title'),
        array('right_block_image'),
        array('right_block_image_hover'),
        array('work_rules_title'),
        array('rule_name', 'rule_description'),
        array('accessories_title'),
        array('accessory_name', 'accessory_icon'),
        array('faq_title'),
        array('faq_question', 'faq_answer'),
        array('section_pay_title', 'pay_main_text'),
        array('pay_btn_left', 'pay_btn_center', 'pay_btn_right'),

    ),
    'title_group' => array(
        'Блок з 3 фото (ліва колонка)',
        '',
        '',
        'Блок з 3 фото (центральна колонка)',
        '',
        '',
        'Блок з 3 фото (права колонка)',
        '',
        '',
        'Секція "Правила роботи"',
        '',
        'Секція "KOWO має:"',
        '',
        'Секція "Поширені питання"',
        '',
        'Секція "Оплата коворкінгу"',
        '',
    ),
));

?>